// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: proto/spaceweave.proto

package spaceweaveproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllocateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size uint64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *AllocateRequest) Reset() {
	*x = AllocateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spaceweave_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateRequest) ProtoMessage() {}

func (x *AllocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spaceweave_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateRequest.ProtoReflect.Descriptor instead.
func (*AllocateRequest) Descriptor() ([]byte, []int) {
	return file_proto_spaceweave_proto_rawDescGZIP(), []int{0}
}

func (x *AllocateRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type AllocateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address uint64 `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *AllocateResponse) Reset() {
	*x = AllocateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spaceweave_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateResponse) ProtoMessage() {}

func (x *AllocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spaceweave_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateResponse.ProtoReflect.Descriptor instead.
func (*AllocateResponse) Descriptor() ([]byte, []int) {
	return file_proto_spaceweave_proto_rawDescGZIP(), []int{1}
}

func (x *AllocateResponse) GetAddress() uint64 {
	if x != nil {
		return x.Address
	}
	return 0
}

type FreeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address uint64 `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`
	Size    uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *FreeRequest) Reset() {
	*x = FreeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spaceweave_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeRequest) ProtoMessage() {}

func (x *FreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spaceweave_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeRequest.ProtoReflect.Descriptor instead.
func (*FreeRequest) Descriptor() ([]byte, []int) {
	return file_proto_spaceweave_proto_rawDescGZIP(), []int{2}
}

func (x *FreeRequest) GetAddress() uint64 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *FreeRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FreeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FreeResponse) Reset() {
	*x = FreeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spaceweave_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeResponse) ProtoMessage() {}

func (x *FreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spaceweave_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeResponse.ProtoReflect.Descriptor instead.
func (*FreeResponse) Descriptor() ([]byte, []int) {
	return file_proto_spaceweave_proto_rawDescGZIP(), []int{3}
}

type GetDiskUtilizationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDiskUtilizationRequest) Reset() {
	*x = GetDiskUtilizationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spaceweave_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDiskUtilizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskUtilizationRequest) ProtoMessage() {}

func (x *GetDiskUtilizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spaceweave_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskUtilizationRequest.ProtoReflect.Descriptor instead.
func (*GetDiskUtilizationRequest) Descriptor() ([]byte, []int) {
	return file_proto_spaceweave_proto_rawDescGZIP(), []int{4}
}

type GetDiskUtilizationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Utilization float32 `protobuf:"fixed32,1,opt,name=utilization,proto3" json:"utilization,omitempty"`
}

func (x *GetDiskUtilizationResponse) Reset() {
	*x = GetDiskUtilizationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spaceweave_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDiskUtilizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskUtilizationResponse) ProtoMessage() {}

func (x *GetDiskUtilizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spaceweave_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskUtilizationResponse.ProtoReflect.Descriptor instead.
func (*GetDiskUtilizationResponse) Descriptor() ([]byte, []int) {
	return file_proto_spaceweave_proto_rawDescGZIP(), []int{5}
}

func (x *GetDiskUtilizationResponse) GetUtilization() float32 {
	if x != nil {
		return x.Utilization
	}
	return 0
}

var File_proto_spaceweave_proto protoreflect.FileDescriptor

var file_proto_spaceweave_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x77, 0x65, 0x61,
	0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x69, 0x73, 0x6b, 0x61, 0x6c,
	0x6c, 0x6f, 0x63, 0x22, 0x25, 0x0a, 0x0f, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x2c, 0x0a, 0x10, 0x41, 0x6c,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x3b, 0x0a, 0x0b, 0x46, 0x72, 0x65, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x46, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x6b,
	0x55, 0x74, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x3e, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x6b, 0x55, 0x74, 0x69,
	0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x32, 0xf6, 0x01, 0x0a, 0x0d, 0x44, 0x69, 0x73, 0x6b, 0x41, 0x6c, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x6f, 0x72, 0x12, 0x45, 0x0a, 0x08, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65,
	0x12, 0x1a, 0x2e, 0x64, 0x69, 0x73, 0x6b, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x2e, 0x41, 0x6c, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64,
	0x69, 0x73, 0x6b, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x04, 0x46,
	0x72, 0x65, 0x65, 0x12, 0x16, 0x2e, 0x64, 0x69, 0x73, 0x6b, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x2e,
	0x46, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x64, 0x69,
	0x73, 0x6b, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x2e, 0x46, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73,
	0x6b, 0x55, 0x74, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x2e, 0x64,
	0x69, 0x73, 0x6b, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x6b,
	0x55, 0x74, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x64, 0x69, 0x73, 0x6b, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x69, 0x73, 0x6b, 0x55, 0x74, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x38, 0x5a, 0x36, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x31, 0x32, 0x31, 0x33,
	0x39, 0x38, 0x37, 0x38, 0x34, 0x32, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x77, 0x65, 0x61, 0x76,
	0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x77, 0x65, 0x61, 0x76, 0x65,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_spaceweave_proto_rawDescOnce sync.Once
	file_proto_spaceweave_proto_rawDescData = file_proto_spaceweave_proto_rawDesc
)

func file_proto_spaceweave_proto_rawDescGZIP() []byte {
	file_proto_spaceweave_proto_rawDescOnce.Do(func() {
		file_proto_spaceweave_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_spaceweave_proto_rawDescData)
	})
	return file_proto_spaceweave_proto_rawDescData
}

var file_proto_spaceweave_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_spaceweave_proto_goTypes = []interface{}{
	(*AllocateRequest)(nil),            // 0: diskalloc.AllocateRequest
	(*AllocateResponse)(nil),           // 1: diskalloc.AllocateResponse
	(*FreeRequest)(nil),                // 2: diskalloc.FreeRequest
	(*FreeResponse)(nil),               // 3: diskalloc.FreeResponse
	(*GetDiskUtilizationRequest)(nil),  // 4: diskalloc.GetDiskUtilizationRequest
	(*GetDiskUtilizationResponse)(nil), // 5: diskalloc.GetDiskUtilizationResponse
}
var file_proto_spaceweave_proto_depIdxs = []int32{
	0, // 0: diskalloc.DiskAllocator.Allocate:input_type -> diskalloc.AllocateRequest
	2, // 1: diskalloc.DiskAllocator.Free:input_type -> diskalloc.FreeRequest
	4, // 2: diskalloc.DiskAllocator.GetDiskUtilization:input_type -> diskalloc.GetDiskUtilizationRequest
	1, // 3: diskalloc.DiskAllocator.Allocate:output_type -> diskalloc.AllocateResponse
	3, // 4: diskalloc.DiskAllocator.Free:output_type -> diskalloc.FreeResponse
	5, // 5: diskalloc.DiskAllocator.GetDiskUtilization:output_type -> diskalloc.GetDiskUtilizationResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_spaceweave_proto_init() }
func file_proto_spaceweave_proto_init() {
	if File_proto_spaceweave_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_spaceweave_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spaceweave_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllocateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spaceweave_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FreeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spaceweave_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FreeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spaceweave_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDiskUtilizationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spaceweave_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDiskUtilizationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_spaceweave_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_spaceweave_proto_goTypes,
		DependencyIndexes: file_proto_spaceweave_proto_depIdxs,
		MessageInfos:      file_proto_spaceweave_proto_msgTypes,
	}.Build()
	File_proto_spaceweave_proto = out.File
	file_proto_spaceweave_proto_rawDesc = nil
	file_proto_spaceweave_proto_goTypes = nil
	file_proto_spaceweave_proto_depIdxs = nil
}
